### ISSUE TITLE
Make a release and add to Stackage

### ISSUE THREAD

**Issue by pepeiborra** [MaartenFaddegon/Hoed#3]
I'd very much like to use Hoed at work, but without a release in Stackage that's very difficult.

**Comment by MaartenFaddegon** [comment]
Will prioritise releasing on Stackage.

**Comment by pepeiborra** [comment]
Can I help in any way to get this released and up in Stackage ?

**Comment by MaartenFaddegon** [comment]
What is delaying me from releasing on Stackage is the dependencies that are not part of Stackage.

Currently I am working on preparing my other project Llibgraph (which is also a dependency for Hoed) to be included in Stackage nightly.

The next step is to address the other dependencies. The new version of Hoed in the Text-branch has less dependencies and is therefore the most likely candidate for releasing on Stackage. Still there are some dependencies (like FPretty) that are outside of my control and not on Stackage yet. 

I'll try to get in touch with their maintainers, but it may take some more time before I am ready to release.

**Comment by pepeiborra** [comment]
The only other missing dependency is RBTree, right ? I've raised https://github.com/wuxb45/Haskell-RBTree/issues/2

**Comment by MaartenFaddegon** [comment]
I actually managed without RBTree In the Text branch I only kept pure derivation of computation trees and RBTree is needed to remove cycles from the approximated computation trees derived from stacks.

Libgraph is on Stackage now. I also contacted Olaf, the maintainer of FPretty.

**Comment by MaartenFaddegon** [comment]
Released Hoed v0.4.0 on Stackage. This is with the new text interface that I was working on, so it might still be a little rough on the edges.
