### ISSUE TITLE
Question: I don't know how to build using stack.

### ISSUE THREAD

**Issue by waddlaw** [MaartenFaddegon/Hoed#5]
I would like to build using the stack.
What should I do?

**Comment by MaartenFaddegon** [comment]
- Make Hoed a dependency of your project
- Import `Debug.Hoed` in the module you want to debug
- Add `observe` annotations to the functions you suspect of being faulty
- Run `stack ghci` then evaluate `runO e` where `e` is the expression that returns an unexpected value

**Comment by waddlaw** [comment]
@MaartenFaddegon 
Thank you for quick reply.

OK.I will be try below documentation example.
https://www.stackage.org/haddock/nightly-2017-09-26/Hoed-0.4.0/Debug-Hoed.html

This code is work?I think so that is there two `main`.
```haskell
import Test.QuickCheck

isOdd :: Int -> Bool
isOdd n = isEven (plusOne n)

isEven :: Int -> Bool
isEven n = mod2 n == 0

plusOne :: Int -> Int
plusOne n = n + 1

mod2 :: Int -> Int
mod2 n = div n 2

prop_isOdd :: Int -> Bool
prop_isOdd x = isOdd (2*x+1)

main :: IO ()
main = printO (prop_isOdd 1)

main :: IO ()
main = quickcheck prop_isOdd
```

**Comment by MaartenFaddegon** [comment]
That is an example of a misbehaving program, QuickCheck is used to demonstrate that the program has a defect.

Starting from the counterexample `prop_isOdd 1` you can find the defect by adding annotations as follows (copied from the documentation you link to):

```
import Debug.Hoed

isOdd :: Int -> Bool
isOdd = observe "isOdd" isOdd'
isOdd' n = isEven (plusOne n)

isEven :: Int -> Bool
isEven = observe "isEven" isEven'
isEven' n = mod2 n == 0

plusOne :: Int -> Int
plusOne = observe "plusOne" plusOne'
plusOne' n = n + 1

mod2 :: Int -> Int
mod2 = observe "mod2" mod2'
mod2' n = div n 2

prop_isOdd :: Int -> Bool
prop_isOdd x = isOdd (2*x+1)

main :: IO ()
main = printO (prop_isOdd 1)
```
Note though that the version released on Stackage does not include the graphical interface, but rather will ask you questions from the interpreter. I need to update the documentation to reflect this.

**Comment by waddlaw** [comment]
Thanks. above code is fine! But, I ran into another problem.

Start interpreter following command:

```bash
$ stack script ex3.hs --resolver nightly-2017-10-02
Using resolver: nightly-2017-10-02 specified on command line
=== program output ===

False

=== program terminated ===
Please wait while the computation tree is constructed...

=== Statistics ===

28 events
4 computation statements
4 nodes + 1 virtual root node in the computation tree
4 edges in computation tree
computation tree has a branch factor of 1.3333333333333333 (i.e the average number of children of non-leaf nodes)

=== Debug Session ===

hdb> help
help              Print this help message.
observe [regexp]  Print computation statements that match the regular
                  expression. Omitting the expression prints all statements.
adb               Start algorithmic debugging.
exit              leave debugging session
```

Now, I tried `adb` command. 

```bash
hdb> adb
======================================================================= [0-0/4]
isOdd <?>
  
  = <?>
```

What mean`<?>` symbol?
And, what should I do after this?

**Comment by MaartenFaddegon** [comment]
The `<?>` symbol is used in special cases only (namely, when you ask the debugger not to trace values of a specific type).

Did you maybe changed the code I shared above? Because for me the debugging session with the above example is as follows:

    [maarten@angua example]$ ghci example.hs 
    GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
    Loaded GHCi configuration from /home/maarten/.ghci
    [1 of 1] Compiling Main             ( example.hs, interpreted )
    Ok, modules loaded: Main.
    *Main> main
    === program output ===
    
    False
    
    === program terminated ===
    Please wait while the computation tree is constructed...
    
    === Statistics ===
    
    28 events
    4 computation statements
    4 nodes + 1 virtual root node in the computation tree
    4 edges in computation tree
    computation tree has a branch factor of 1.3333333333333333 (i.e the average number of children of non-leaf nodes)
    
    === Debug Session ===
    
    hdb> adb
    ======================================================================= [0-0/4]
    isOdd 3
      
      = False
    ? wrong
    ======================================================================= [1-0/4]
    plusOne 3
      
      = 4
    ? right
    ======================================================================= [1-1/4]
    isOdd 3
      
      = False
    ? wrong
    ======================================================================= [1-1/4]
    isEven 4
      
      = False
    wrong    
    ======================================================================= [2-1/4]
    mod2 4
      
      = 2
    ? wrong
    ======================================================================= [3-1/4]
    Fault located! In:
    mod2 4
      
      = 2

**Comment by waddlaw** [comment]
My full source code:

```haskell
# example.hs
import Debug.Hoed

isOdd :: Int -> Bool
isOdd = observe "isOdd" isOdd'

isOdd' n = isEven (plusOne n)

isEven :: Int -> Bool
isEven = observe "isEven" isEven'

isEven' n = mod2 n == 0

plusOne :: Int -> Int
plusOne = observe "plusOne" plusOne'

plusOne' n = n + 1

mod2 :: Int -> Int
mod2 = observe "mod2" mod2'

mod2' n = div n 2

prop_isOdd :: Int -> Bool
prop_isOdd x = isOdd (2 * x + 1)

main :: IO ()
main = printO (prop_isOdd 1)
```



```bash
$ stack script example.hs --resolver nightly-2017-10-09
Using resolver: nightly-2017-10-09 specified on command line
=== program output ===

False

=== program terminated ===
Please wait while the computation tree is constructed...

=== Statistics ===

28 events
4 computation statements
4 nodes + 1 virtual root node in the computation tree
4 edges in computation tree
computation tree has a branch factor of 1.3333333333333333 (i.e the average number of children of non-leaf nodes)

=== Debug Session ===

hdb> adb
======================================================================= [0-0/4]
isOdd <?>
  
  = <?>
? wrong
======================================================================= [1-0/4]
plusOne <?>
  
  = <?>
? right
======================================================================= [1-1/4]
isOdd <?>
  
  = <?>
wrong       
======================================================================= [1-1/4]
isEven <?>
  
  = <?>
? wrong  
======================================================================= [2-1/4]
mod2 <?>
  
  = <?>
? wrong
======================================================================= [3-1/4]
Fault located! In:
mod2 <?>
  
  = <?>
```

It remains `<?>`. Is something wrong?

## Environment

```bash
$ stack --version
Version 1.5.1, Git revision 2a22d1577afb5aef6cf6f80255399cbfa16f7893 x86_64 hpack-0.18.1

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu Artful Aardvark (development branch)"
```

**Comment by MaartenFaddegon** [comment]
[This example project](https://github.com/MaartenFaddegon/Hoed-example-project) shows how to debug your Stack project with Hoed.

I am not quite sure why your stack script command behaves so strangely. For now I think you should consider stack script as not supported by Hoed.
